project_id = "minylqvqwrawlzrjgazm"

[functions.send-notification]
verify_jwt = false

[functions.send-appointment-notification]
verify_jwt = false

[functions.send-contact-notification]
verify_jwt = false

[functions.generate-vcard-bio]
verify_jwt = false

[functions.vcard-og-image]
verify_jwt = false

[functions.vcard-chat]
verify_jwt = false